### ISSUE TITLE
Sourcing Dataset

### ISSUE THREAD

**Issue by amiller68** [banyancomputer/banyan-cli#122]

**Comment by amiller68** [comment]
We need to source an appropriate dataset for our DCENT demo.

**Comment by amiller68** [comment]
We need an API we can call in a terminal environment that will download a large, publicly accessible dataset that we can apply for datacap for.

**Comment by amiller68** [comment]
Another option is we formalize a request for Datacap that we can use for Fake data -- either way we need to get datacap approved

**Comment by anjor** [comment]
What sort of scale are you looking for? In the past I have used the [AWS marketplace datasets](https://aws.amazon.com/marketplace/search/results?trk=8384929b-0eb1-4af3-8996-07aa409646bc&sc_channel=el&FULFILLMENT_OPTION_TYPE=DATA_EXCHANGE&CONTRACT_TYPE=OPEN_DATA_LICENSES&filters=FULFILLMENT_OPTION_TYPE%2CCONTRACT_TYPE) for testing purposes.

**Comment by laudiacay** [comment]
we managed this right
