### ISSUE TITLE
find or build a tool to check that the filesystem BEFORE and AFTER you run some code is exactly the same. this is a prerequisite to all others.

### ISSUE THREAD

**Issue by laudiacay** [banyancomputer/banyan-cli#14]

**Comment by ghost** [comment]
https://github.com/banyancomputer/dataprep/pull/48

**Comment by amiller68** [comment]
Thea found this library which asserts if two dirs are the same. This should be fine for integration tests on diff edge cases:
https://docs.rs/dir-assert/latest/dir_assert/
I found this solution which might save space in a dev environment where we would unpack to the same dir we packed from:
https://unix.stackexchange.com/questions/453385/shell-check-if-any-file-in-directory-has-changed

**Comment by amiller68** [comment]
Considering this one closed. Good work @thea-exe :)
