### ISSUE TITLE
Motivation?

### ISSUE THREAD

**Issue by anjor** [banyancomputer/banyan-cli#47]
I have been thinking about data prep for filecoin deal making recently and stumbled upon this repo. I was wondering what the motivation behind this effort was? What was missing from some of the existing tools such as:

https://github.com/tech-greedy/go-generate-car
https://github.com/ribasushi/DAGger

or any other that I don't know about?

cc: @laudiacay

**Comment by laudiacay** [comment]
Max speed, adding compression + encryption all in the same pipeline, with
encryption done file by file or even more granularly :) it’s necessary for
a product we’re building.

Happy to call with you if you want!

**Comment by amiller68** [comment]
Hi @anjor ! As @laudiacay said we'd be more than happy to hop on a call and talk through the motivation. Feel free to reach out to me on Filecoin slack @krondor.BANYAN and we can set something up. For now I'm closing this issue.

**Comment by anjor** [comment]
Thanks for the offer -- I will reach out once I have more information at my end to set up a chat.

Regardless, whenever you guys are done with the work it would be great to see some performance numbers -- what sort of throughput you observe, for instance.

@amiller68 @laudiacay
